version: '1'
services:
  onu:
    build: ./docker
    user: 'local'
    container_name: onu
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./:/var/www/html
    environment:
      MSQL_HOST: db
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      SERVER_PORT: ${SERVER_PORT}

  db:
    image: mysql
    ports:
      - "3306:3306"
    container_name: mysql_onu
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
